#ifndef LIBKPL_APP_ERRORS_H
#define LIBKPL_APP_ERRORS_H

#define KPL_SW_SUCCESS 0x9000
#define KPL_SW_UNKNOWN_INSTR 0x6D00
#define KPL_SW_INVALID_CLS 0x6E00
#define KPL_SW_INVALID_PARAMETER 0x6802
#define KPL_SW_UNAUTHORIZED_ACCESS 0x6820
#define KPL_SW_EMPTY_SLOT 0x6821

#endif
