list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})
if(NOT TARGET sodium)
  find_package(sodium REQUIRED)
endif()
if(NOT TARGET HIDAPI::hidapi)
  find_package(HIDAPI REQUIRED)
endif()
include("${CMAKE_CURRENT_LIST_DIR}/kpl-target.cmake")
