name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: docker://aguinet/ledger_keepass:latest

    steps:
    - uses: actions/checkout@v2
    - name: Tests
      run: |
        # Python dependencies have been installed in the root home directory
        HOME=/root ci/docker_tests.sh $GITHUB_WORKSPACE
