name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Tests
      run: |
        docker run -v $GITHUB_WORKSPACE:/pwd aguinet/ledger_keepass:latest /bin/bash /pwd/ci/docker_tests.sh /pwd
